In [2]:
sentence = "Life is short I use Python"

In [3]:
words = sentence.split()
print(words)

['Life', 'is', 'short', 'I', 'use', 'Python']


In [4]:
sorted_words = sorted(words)

In [9]:
dc = {}
dc = {sw:i for i, sw in enumerate(sorted_words)}
print(dc)

{'I': 0, 'Life': 1, 'Python': 2, 'is': 3, 'short': 4, 'use': 5}


In [10]:
s_idx = [dc[w] for i, w in enumerate(words)]

In [11]:
s_idx

[1, 3, 4, 0, 5, 2]

In [12]:
import torch

In [13]:
t_sentence = torch.tensor(s_idx)

In [14]:
t_sentence

tensor([1, 3, 4, 0, 5, 2])

In [15]:
torch.manual_seed(9)

In [16]:
embed = torch.nn.Embedding(6, 16)

In [18]:
embedded_sentence = embed(t_sentence).detach()

In [19]:
embedded_sentence.shape

torch.Size([6, 16])

In [22]:
d_q, d_k, d_v = 24, 24, 28

In [26]:
d = embedded_sentence.shape[1]

In [27]:
W_query = torch.nn.Parameter(torch.rand(d_q, d))
W_key = torch.nn.Parameter(torch.rand(d_k, d))
W_value = torch.nn.Parameter(torch.rand(d_v, d))

In [28]:
keys = W_key.matmul(embedded_sentence.T).T
query = W_query.matmul(embedded_sentence.T).T
value = W_value.matmul(embedded_sentence.T).T

In [31]:
x_3 = embedded_sentence[3]

In [32]:
q_3 = W_query.matmul(x_3)

In [58]:
keys.shape

torch.Size([6, 24])

In [59]:
q_3.shape

torch.Size([24])

In [33]:
omega_3 = q_3.matmul(keys.T)

In [34]:
import torch.nn.functional as F

In [35]:
attention_weights_2 = F.softmax(omega_3 / d_k**0.5, dim=0)

In [36]:
omega_3.shape

torch.Size([6])

In [37]:
omega_3

tensor([-24.7829,   0.0276,   7.0092,  -0.8207,  -5.1865,   7.7086],
       grad_fn=<SqueezeBackward4>)

In [38]:
attention_weights_2

tensor([0.0006, 0.0897, 0.3730, 0.0754, 0.0309, 0.4303],
       grad_fn=<SoftmaxBackward0>)

In [39]:
attention_weights_2.sum()

tensor(1., grad_fn=<SumBackward0>)

In [41]:
context_vector_2 = attention_weights_2.matmul(value)

In [42]:
h = 3
multihead_W_q = torch.nn.Parameter(torch.rand(h, d_q, d))
multihead_W_k = torch.nn.Parameter(torch.rand(h, d_k, d))
multihead_W_v = torch.nn.Parameter(torch.rand(h, d_v, d))

In [43]:
multihead_q_3 = multihead_W_q.matmul(x_3)

In [44]:
multihead_q_3.shape

torch.Size([3, 24])

In [45]:
multihead_k_3 = multihead_W_k.matmul(x_3)
multihead_v_3 = multihead_W_v.matmul(x_3)

In [47]:
embedded_sentence

tensor([[-1.1433,  0.8289,  0.9534,  0.2948,  1.5159, -1.5261, -1.5409, -0.7916,
          0.3971,  0.4058, -0.5274, -1.3820, -0.2745, -1.0569, -1.5705, -1.4153],
        [-1.3809, -0.1477,  1.5924, -0.4786, -0.3314, -1.1735, -0.7365,  0.5320,
          1.0343,  0.2972,  0.5447, -1.2267,  1.6075, -1.1517,  0.7555, -0.6666],
        [ 1.2391,  0.2612,  0.8609, -1.0079,  0.2578,  2.0466, -0.6811,  0.9115,
          0.0544, -0.0755,  0.7999, -0.3039, -0.6900,  1.0410, -1.1499, -0.1272],
        [-1.0674, -0.7172,  1.0897, -1.5747,  1.4460,  0.6191, -0.7737, -2.4656,
          0.9968,  0.4524, -0.3464, -0.7245,  1.7059,  2.2282, -0.0677,  0.2331],
        [ 0.3794, -0.8496,  0.3060,  0.0850,  0.9101, -1.9523,  0.9402,  0.4649,
         -0.7502, -0.2891, -0.0708,  0.0069,  0.2617, -0.6611,  0.7149,  0.2220],
        [ 1.9437,  0.9387,  0.2648, -0.8008,  0.3755, -0.1700,  0.4489,  0.6473,
         -0.7958,  1.5887, -1.5875, -0.6345,  0.6519, -1.3103,  1.8011, -0.9562]])

In [48]:
embedded_sentence.shape

torch.Size([6, 16])

In [50]:
stacked_inputs = embedded_sentence.T.repeat(3, 1, 1)

In [51]:
stacked_inputs.shape

torch.Size([3, 16, 6])

In [53]:
multihead_keys = torch.bmm(multihead_W_k, stacked_inputs)
multihead_values = torch.bmm(multihead_W_v, stacked_inputs)

In [56]:
multihead_keys.shape

torch.Size([3, 24, 6])

In [57]:
multihead_q_3.shape

torch.Size([3, 24])

In [55]:
omega_3 = multihead_q_3.bmm(multihead_keys)

RuntimeError: batch1 must be a 3D tensor

In [78]:
xx = torch.tensor([1, 1, 1])

In [86]:
yy = torch.tensor([[3, 5], [3, 5], [3, 5]])

In [87]:
zz = xx.matmul(yy)

In [88]:
zz

tensor([ 9, 15])